---
name: Run VM-MANAGER-BINARIES-PR-MERGE

on:
  pull_request:
    types: [closed]
    branches: "**"

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    uses: projectceladon/celadonworkflows/.github/workflows/trigger_ci.yml@v1.0
    with:
      EVENT: ${{ toJSON(github.event) }}